//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBcontext.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public Nullable<int> Price { get; set; }
        public string ImageLink { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> SellerID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
