//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logindetail
    {
        public int id { get; set; }
        public Nullable<int> staff_id { get; set; }
        public Nullable<System.DateTime> login_time { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string token { get; set; }
    
        public virtual staff staff { get; set; }
    }
}
